spring:
  application:
    name: data-service-oracle
  profiles:
    active: dev
logging:
  level:
    root: trace
seata:
  data-source-proxy-mode: XA
  enable-auto-data-source-proxy: true #关闭数据源自动代理:false 开启:true


