spring:
  cloud:
    nacos:
      config:
        namespace:
        group:
        username: nacos
        password: nacos
      discovery:
        namespace:
        group:
        username: nacos
        password: nacos
logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug
management:
  endpoints:
    web:
      exposure:
        include: '*'

